### ISSUE TITLE
ImportError: cannot import name 'EMPTYSTRING' from 'smtpd' (/usr/lib/python3.7/smtpd.py)

### ISSUE THREAD

**Issue by tommycw1** [gonzalezcalleja/smtp2mqtt#1]
python3.7 smtp2mqtt.py --mqtttopic "camera/test" --mqtthost 127.0.0.1 --mqttport 1883 --smtphost 192.168.1.100 --smtpport 10025 --smtpusername test --smtppassword testpw

Traceback (most recent call last):
  File "smtp2mqtt.py", line 7, in <module>
    from secure_smtpd import SMTPServer, LOG_NAME
  File "/home/tom/.local/lib/python3.7/site-packages/secure_smtpd/__init__.py", line 3, in <module>
    from .smtp_server import SMTPServer
  File "/home/tom/.local/lib/python3.7/site-packages/secure_smtpd/smtp_server.py", line 4, in <module>
    from .smtp_channel import SMTPChannel
  File "/home/tom/.local/lib/python3.7/site-packages/secure_smtpd/smtp_channel.py", line 5, in <module>
    from smtpd import NEWLINE, EMPTYSTRING
ImportError: cannot import name 'EMPTYSTRING' from 'smtpd' (/usr/lib/python3.7/smtpd.py)

**Comment by tommycw1** [comment]
OK it looks like the secure-smtpd package was broken, causing this error.  I installed with pip and this is the version I got, but apparently this was fixed in 2017 with this commit:

https://github.com/bcoe/secure-smtpd/commit/fe99f2add1a88ce0d93c892a85280c37f03f7993

**Comment by cba42** [comment]
Hi @tommycw1 ,
I am getting the same error, can you please detail how you fixed it ?
I installed using pip and I got the latest version 3.0.0 of secure-smtpd
Thanks !
